//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Jamnik.cpp
//  @ Date : 09.03.2023
//  @ Author :
//
//


#include "Jamnik.h"

string Jamnik::getImie() {
    return imie;
}

void Jamnik::setImie(string imie) {
    this->imie = imie;
}

float Jamnik::getDlugoscCiala() {
    return dlugoscCiala;
}

void Jamnik::setDlugoscCiala(float dlugosc) {
    this->dlugoscCiala = dlugosc;
}

