//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Jamnik.h
//  @ Date : 09.03.2023
//  @ Author : 
//
//


#if !defined(_JAMNIK_H)
#define _JAMNIK_H

#include "Pies.h"

class Jamnik : public Pies {
public:
	string getImie();
	void setImie(string imie);
	float getDlugoscCiala();
	void setDlugoscCiala(float dlugosc);
private:
	string imie;
	float dlugoscCiala;
};

#endif  //_JAMNIK_H
