//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Pies.cpp
//  @ Date : 09.03.2023
//  @ Author :
//
//


#include "Pies.h"
#include <iostream>

string Pies::getKolorSiersci() {
    return kolorSiersci;
}

void Pies::setKoloSiersci(string kolor) {
    this->kolorSiersci = kolor;
}

string Pies::getRodzajUszu() {
    return rodzajUszu;
}

void Pies::setRodzajUszu(string uszy) {
    this->rodzajUszu = uszy;
}

void Pies::dajGlos() {
    std::cout << "Hau hau\n";
}

