//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Ssak.h
//  @ Date : 09.03.2023
//  @ Author : 
//
//


#include <string>
#if !defined(_SSAK_H)
#define _SSAK_H

using namespace std;


class Ssak {
public:
	string getPlec();
	void setPlec(string plec);
	int getWiek();
	void setWiek(int wiek);
private:
	string plec;
	int wiek;
};

#endif  //_SSAK_H
