//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Ssak.cpp
//  @ Date : 09.03.2023
//  @ Author :
//
//


#include "Ssak.h"

string Ssak::getPlec() {
    return plec;
}

void Ssak::setPlec(string plec) {
    this->plec = plec;
}

int Ssak::getWiek() {
    return wiek;
}

void Ssak::setWiek(int wiek) {
    this->wiek = wiek;
}

