//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Bicycle.cpp
//  @ Date : 23.03.2023
//  @ Author :
//
//


#include "Bicycle.h"

Bicycle::Bicycle(int serialNumber, string make, string type, string colour) {
    this->serial_number = serialNumber;
    this->make = make;
    this->type = type;
    this->colour = colour;
}

int Bicycle::getSerialNumber() {
    return serial_number;
}

void Bicycle::setSerialNumber(int serialNumber) {
    this->serial_number = serial_number;
}

string Bicycle::getMake() {
    return make;
}

void Bicycle::setMake(string make) {
    this->make = make;
}

string Bicycle::getType() {
    return type;
}

void Bicycle::setType(string type) {
    this->type = type;
}

string Bicycle::getColour() {
    return colour;
}

void Bicycle::setColour(string colour) {
    this->colour = colour;
}

void Bicycle::printData() {
    cout << "Bicycle: Serial Number - " << serial_number << ", make - " << make
    << ", type - " << type << ", colour - " << colour << "\n";
}

