//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Person.cpp
//  @ Date : 23.03.2023
//  @ Author :
//
//


#include "Person.h"

Person::Person(string firstName, string lastName, int age) {
    this->first_name = firstName;
    this->last_name = lastName;
    this->age = age;
}

string Person::getFirstName() {
    return first_name;
}

void Person::setFirstName(string name) {
    this->first_name = name;
}

string Person::getLastName() {
    return last_name;
}

void Person::setLastName(string name) {
    this->last_name = name;
}

int Person::getAge() {
    return age;
}

void Person::setAge(int age) {
    this->age = age;
}

Bicycle* Person::getBicycle(int serialNumber) {
    for(int i=0; i<owned_bicycles.size(); i++){
        if(owned_bicycles.at(i)->getSerialNumber() == serialNumber){
            return owned_bicycles.at(i);
        }
    }
    cout << "This person doesn't own a bicycle of this serial number\n";
    return nullptr;
}

void Person::addBicycle(Bicycle* bicycle) {
    owned_bicycles.push_back(bicycle);
}

void Person::removeBicycle(int serialNumber) {
    for(int i=0; i<owned_bicycles.size(); i++){
        if(owned_bicycles.at(i)->getSerialNumber() == serialNumber){
            owned_bicycles.erase(owned_bicycles.begin()+i);
            return;
        }
    }
    cout << "This person doesn't own a bicycle of this serial number\n";
}

void Person::printData() {
    cout << "Person:\nFirst Name - " << first_name << "\nLast Name - " << last_name
    << "\nAge - " << age << "\n";
    for(int i=0; i<owned_bicycles.size(); i++){
        owned_bicycles.at(i)->printData();
    }
}

