//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Bike.h
//  @ Date : 22/03/2023
//  @ Author :
//
//


#include <string>
#if !defined(_BIKE_H)
#define _BIKE_H

using namespace std;

class Bike {
public:
	Bike();
	~Bike();
	int getId();
	void setId(int id);
	string getModel();
	void setModel(string model);
	string getColour();
	void setColour(string colour);
private:
	int id;
	string model;
	string colour;
};

#endif  //_BIKE_H
