//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : BikeRental.h
//  @ Date : 22/03/2023
//  @ Author :
//
//


#if !defined(_BIKERENTAL_H)
#define _BIKERENTAL_H

#include "Bike.h"


class BikeRental {
public:
	BikeRental(string name);
	~BikeRental();
	string getName();
	void setName(string name);
	string getAddress();
	void setAddress(string address);
	string getPhoneNumber();
	void setPhoneNumber(string phoneNumber);
	void printBikeData();
	void setBikeData(int id, string model, string colour);
	void printData();
private:
	string name;
	string address;
	string phone_number;
	Bike* bike;
};

#endif  //_BIKERENTAL_H
