//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Car.h
//  @ Date : 16.03.2023
//  @ Author :
//
//


#include <iostream>
#include <string>
#if !defined(_CAR_H)
#define _CAR_H

using namespace std;
class Person;
class Car {
public:
	Car(string make, string model);
	string getMake();
	void setMake(string make);
	string getModel();
	void setModel(string model);
	Person* getPerson();
	void setPerson(Person* personPtr);
	void printData();
private:
	string make;
	string model;
	Person* owner;
};

#endif  //_CAR_H
