//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Car.cpp
//  @ Date : 16.03.2023
//  @ Author :
//
//


#include "Car.h"

Car::Car(string make, string model) {
    this->make = make;
    this->model = model;
}

string Car::getMake() {
    return make;
}

void Car::setMake(string make) {
    this->make = make;
}

string Car::getModel() {
    return model;
}

void Car::setModel(string model) {
    this->model = model;
}

Person* Car::getPerson() {
    return owner;
}

void Car::setPerson(Person* personPtr) {
    this->owner = personPtr;
}

void Car::printData() {
    cout << "Make: " << make << "\nModel: " << model << "\n";
}

