//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Person.cpp
//  @ Date : 16.03.2023
//  @ Author :
//
//


#include "Person.h"

Person::Person(string firstName, string lastName, int age) {
    this->first_name = firstName;
    this->last_name = lastName;
    this->age = age;
}

string Person::getFirstName() {
    return first_name;
}

void Person::setFirstName(string name) {
    this->first_name = name;
}

string Person::getLastName() {
    return last_name;
}

void Person::setLastName(string name) {
    this->last_name = name;
}

int Person::getAge() {
    return age;
}

void Person::setAge(int age) {
    this->age = age;
}

Car* Person::getCar() {
    return owned_car;
}

void Person::setCar(Car* carPtr) {
    this->owned_car = carPtr;
}

void Person::printData() {
    cout << "First Name: " << first_name << "\nLast Name: " << last_name << "\nAge: " << age << "\n";
}

