//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Bernouli.h
//  @ Date : 26/04/2023
//  @ Author :
//
//

#include "Power.h"
#include "Newton.h"

#if !defined(_BERNOULI_H)
#define _BERNOULI_H


class Bernouli {
public:
	Bernouli();
	~Bernouli();
	long double bernouli(float p, int n, int k);
private:
	Power* powerPtr;
	Newton* newtonPtr;
};

#endif  //_BERNOULI_H
