//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Power.h
//  @ Date : 26/04/2023
//  @ Author :
//
//


#if !defined(_POWER_H)
#define _POWER_H


class Power {
public:
	long double power(float base, int index);
	long double powerIter(float base, int index);
};

#endif  //_POWER_H
