//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Computer.cpp
//  @ Date : 30/03/2023
//  @ Author :
//
//


#include "Computer.h"

Computer::Computer(string operatingSystem) {
    this->operating_system = operatingSystem;
    connected_to_network = false;
}

string Computer::getOperatingSystem() {
    return operating_system;
}

void Computer::setOperatingSystem(string os) {
    operating_system = os;
}

bool Computer::isConnectedToNetwork() {
    return connected_to_network;
}

void Computer::connectToNetwork() {
    connected_to_network = true;
    cout << "Computer connected to network\n";
}

void Computer::disconnectFromNetwork() {
    connected_to_network = false;
    cout << "Computer disconnected from network\n";
}

void Computer::printData() {
    cout << "\tComputer: Operating system - " << operating_system
    << ", Connected to local network - " << connected_to_network << "\n";
}

