//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Workstation.h
//  @ Date : 30/03/2023
//  @ Author :
//
//

#include "Computer.h"

#if !defined(_WORKSTATION_H)
#define _WORKSTATION_H

using namespace std;

class Workstation {
public:
	Workstation(int number);
	~Workstation();
	int getWorkstationNumber();
	void setWorkstationNumber(int number);
	bool isOccupied();
	void occupy();
	void free();
	bool isEquippedWithComputer();
	void addComputer(Computer* computerPtr);
	void removeComputer();
	void printData();
private:
	int number;
	bool occupied;
	bool equipped_with_computer;
	Computer* computer;
};

#endif  //_WORKSTATION_H
