//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Workroom.cpp
//  @ Date : 30/03/2023
//  @ Author :
//
//


#include "Workroom.h"

Workroom::Workroom(int floorNumber, int roomNumber, int numberOfWorkstations) {
    this->floor_number = floorNumber;
    this->room_number = roomNumber;
    this->number_of_workstations = numberOfWorkstations;

    for(int i = 0; i < number_of_workstations; i++){
        workstations.push_back(new Workstation(i+1));
    }
}

Workroom::~Workroom() {
    for(int i = 0; i < number_of_workstations; i++){
        delete workstations.at(i);
    }
}

int Workroom::getFloorNumber() {
    return floor_number;
}

int Workroom::getRoomNumber() {
    return room_number;
}

int Workroom::getNumberOfWorkstations() {
    return number_of_workstations;
}

Workstation* Workroom::getWorkstation(int number) {
    return workstations.at(number-1);
}

void Workroom::workstationData(int number) {
    workstations.at(number-1)->printData();
}

void Workroom::allWorkstations() {
    cout << "Workstations:\n";
    for(int i = 0; i < number_of_workstations; i++){
        workstations.at(i)->printData();
    }
}

