//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Person.h
//  @ Date : 21/03/2023
//  @ Author :
//
//

#include <string>
#if !defined(_PERSON_H)
#define _PERSON_H

using namespace std;

class Person {
public:
	Person(string firstName, string lastName, int age);
	string getFirstName();
	void setFirstName(string name);
	string getLastName();
	void setLastName(string name);
	int getAge();
	void setAge(int age);
	void printData();
private:
	string first_name;
	string last_name;
	int age;
};

#endif  //_PERSON_H
