//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Store.cpp
//  @ Date : 21/03/2023
//  @ Author :
//
//

#include <iostream>
#include "Store.h"

Store::Store(string name, string typeOfProducts) {
    this->name = name;
    this->type_of_products = typeOfProducts;
}

string Store::getName() {
    return name;
}

void Store::setName(string name) {
    this->name = name;
}

Person* Store::getEmployee() {
    return employee;
}

void Store::setEmployee(Person* person) {
    this->employee = person;
}

string Store::getTypeOfProducts() {
    return type_of_products;
}

void Store::setTypeOfProducts(string type) {
    this->type_of_products = type;
}

void Store::printData() {
    cout << "Name: " << name << "\nType of Sold Products: " << type_of_products << "\nEmployee:\n";
    employee->printData();
}

