//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Bernouli.cpp
//  @ Date : 09/05/2023
//  @ Author :
//
//


#include "Bernouli.h"

Bernouli::Bernouli() {

}

Bernouli::~Bernouli() {

}

long double Bernouli::bernouli(float p, int n, int k, Power* powerPtr, Newton* newtonPtr, Factorial* factorialPtr) {
    float q = 1 - p;
    return newtonPtr->newton(n, k) * powerPtr->power(p, k) * powerPtr->power(q, n-k);
}

