//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Factorial.cpp
//  @ Date : 09/05/2023
//  @ Author :
//
//


#include "Factorial.h"

long double Factorial::factorial(int number) {
    if(number == 0) {
        return 1;
    }
    return number * factorial(number-1);
}

long double Factorial::factorialIter(int number) {
    long double result = 1;
    for(int i = 1; i <= number; i++) {
        result *= i;
    }
    return result;
}

