//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Factorial.h
//  @ Date : 09/05/2023
//  @ Author : 
//
//


#if !defined(_FACTORIAL_H)
#define _FACTORIAL_H


class Factorial {
public:
	long double factorial(int number);
	long double factorialIter(int number);
};

#endif  //_FACTORIAL_H
