//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : System.cpp
//  @ Date : 13.04.2023
//  @ Author :
//
//


#include "System.h"

void System::login() {
    string identifier;
    string password;
    cout << "Log in\nIdentifier: ";
    cin >> identifier;
    cout << "Password: ";
    cin >> password;

    for(int i = 0; i < user_list.size(); i++){
        if(user_list[i] != nullptr && identifier == user_list[i]->getIdentifier()){
            if(password == user_list[i]->getPassword()){
                cout << "Login successful.\n\n";
                return;
            } else {
                cout << "Incorrect password. Please try again.\n";
                login();
                return;
            }
        }
    }
    cout << "No such user exists. Please create a new user.\n\n";
    newRegister();
}

void System::newRegister() {
    string identifier;
    string password;
    cout << "Register\n";
    cout << "New User Identifier: ";
    cin >> identifier;
    cout << "New Password: ";
    cin >> password;
    addUser(identifier, password);
    cout << "Register successful.\n\n";
    login();
}

void System::addUser(string id, string password) {
    user_list.push_back(new User(id, password));
}

