//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : User.cpp
//  @ Date : 13.04.2023
//  @ Author :
//
//


#include "User.h"

User::User(string id, string password) {
    this->identifier = id;
    this->password = password;
}

string User::getIdentifier() {
    return identifier;
}

void User::setIdentifier(string id) {
    this->identifier = id;
}

string User::getPassword() {
    return password;
}

void User::setPassword(string password) {
    this->password = password;
}

