//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : BikeRental.cpp
//  @ Date : 29/03/2023
//  @ Author :
//
//


#include "BikeRental.h"

BikeRental::BikeRental(string name, int bikeId, string bikeModel, string bikeColour) {
    this->name = name;
    bikes.push_back(new Bike(bikeId, bikeModel, bikeColour));
}

BikeRental::~BikeRental() {
    for(int i=0; i<bikes.size(); i++){
        delete bikes.at(i);
    }
}

string BikeRental::getName() {
    return name;
}

void BikeRental::setName(string name) {
    this->name = name;
}

string BikeRental::getAddress() {
    return address;
}

void BikeRental::setAddress(string address) {
    this->address = address;
}

string BikeRental::getPhoneNumber() {
    return phone_number;
}

void BikeRental::setPhoneNumber(string phoneNumber) {
    this->phone_number = phoneNumber;
}

void BikeRental::addBike(Bike* bike) {
    bikes.push_back(bike);
}

void BikeRental::removeBike(int id) {
    for(int i=0; i<bikes.size(); i++){
        if(bikes.at(i)->getId() == id){
            bikes.erase(bikes.begin()+i);
            return;
        }
    }
}

void BikeRental::printData() {
    cout << "Bike Rental\nName: " << name << "\nAddress: " << address
    << "\nPhone number: " << phone_number << "\nBikes:\n";
    for(int i=0; i<bikes.size(); i++){
        bikes.at(i)->printData();
    }
}
