//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Bike.h
//  @ Date : 29/03/2023
//  @ Author :
//
//

#include <iostream>
#include <string>

#if !defined(_BIKE_H)
#define _BIKE_H

using namespace std;

class Bike {
public:
	Bike(int id, string model, string colour);
	~Bike();
	int getId();
	void setId(int id);
	string getModel();
	void setModel(string model);
	string getColour();
	void setColour(string colour);
	void printData();
private:
	int id;
	string model;
	string colour;
};

#endif  //_BIKE_H
