//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : BikeRental.h
//  @ Date : 29/03/2023
//  @ Author :
//
//

#include <vector>
#include "Bike.h"

#if !defined(_BIKERENTAL_H)
#define _BIKERENTAL_H

using namespace std;

class BikeRental {
public:
	BikeRental(string name, int bikeId, string bikeModel, string bikeColour);
	~BikeRental();
	string getName();
	void setName(string name);
	string getAddress();
	void setAddress(string address);
	string getPhoneNumber();
	void setPhoneNumber(string phoneNumber);
	void addBike(Bike* bike);
	void removeBike(int id);
	void printData();
private:
	string name;
	string address;
	string phone_number;
	vector<Bike*> bikes;
};

#endif  //_BIKERENTAL_H
