//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Bike.cpp
//  @ Date : 29/03/2023
//  @ Author :
//
//


#include "Bike.h"

Bike::Bike(int id, string model, string colour) {
    this->id = id;
    this->model = model;
    this->colour = colour;
}

Bike::~Bike() {

}

int Bike::getId() {
    return id;
}

void Bike::setId(int id) {
    this->id = id;
}

string Bike::getModel() {
    return model;
}

void Bike::setModel(string model) {
    this->model = model;
}

string Bike::getColour() {
    return colour;
}

void Bike::setColour(string colour) {
    this->colour = colour;
}

void Bike::printData() {
    cout << "Id - " << id << ", Model - " << model << ", Colour - " << colour << "\n";
}

