//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Store.h
//  @ Date : 29/03/2023
//  @ Author :
//
//

#include <vector>
#include "Person.h"

#if !defined(_STORE_H)
#define _STORE_H

using namespace std;

class Store {
public:
	Store(string name, string typeOfProducts);
	~Store();
	string getStoreName();
	void setStoreName(string name);
	string getTypeOfProducts();
	void setTypeOfProducts(string typeOfProducts);
	void addEmployee(Person* employee);
	void removeEmployee(string firstName, string lastName);
	void printData();
private:
	string store_name;
	string type_of_products;
	vector<Person*> employees;
};

#endif  //_STORE_H
