//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Builder.h
//  @ Date : 16.03.2023
//  @ Author :
//
//


#include <string>
#if !defined(_BUILDER_H)
#define _BUILDER_H

using namespace std;


class Builder {
public:
	Builder(string name, int yearsOfExperience);
	string getName();
	void setName(string name);
	int getYearsOfExperience();
	void setYearsOfExperience(int years);
	void useAScrewdriver();
	void useAHammer();
	void useAWelder();
private:
	string name;
	int years_of_experience;
};

#endif  //_BUILDER_H
