//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Builder.cpp
//  @ Date : 16.03.2023
//  @ Author :
//
//


#include "Builder.h"

Builder::Builder(string name, int yearsOfExperience) {
    this->name = name;
    this->years_of_experience = yearsOfExperience;
}

string Builder::getName() {
    return name;
}

void Builder::setName(string name) {
    this->name = name;
}

int Builder::getYearsOfExperience() {
    return years_of_experience;
}

void Builder::setYearsOfExperience(int years) {
    this->years_of_experience = years;
}

void Builder::useAScrewdriver() {
    printf("A screwdriver has been used\n");
}

void Builder::useAHammer() {
    printf("A hammer has been used\n");
}

void Builder::useAWelder() {
    printf("A welder has been used\n");
}

