//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Mechanic.h
//  @ Date : 16.03.2023
//  @ Author :
//
//


#if !defined(_MECHANIC_H)
#define _MECHANIC_H

#include "Builder.h"

class Mechanic {
public:
	Mechanic(string name, int yearsOfExperience);
	string getName();
	void setName(string name);
	int getYearsOfExperience();
	void setYearsOfExperience(int years);
	void useAWelder(Builder *builderPtr);
	void useAnalisysDevice();
private:
	string name;
	int years_of_experience;
};

#endif  //_MECHANIC_H
