//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Mechanic.cpp
//  @ Date : 16.03.2023
//  @ Author :
//
//


#include "Mechanic.h"
#include "Builder.h"

Mechanic::Mechanic(string name, int yearsOfExperience) {
    this->name = name;
    this->years_of_experience = yearsOfExperience;
}

string Mechanic::getName() {
    return name;
}

void Mechanic::setName(string name) {
    this->name = name;
}

int Mechanic::getYearsOfExperience() {
    return years_of_experience;
}

void Mechanic::setYearsOfExperience(int years) {
    this->years_of_experience = years;
}

void Mechanic::useAWelder(Builder *builderPtr) {
    builderPtr->useAWelder();
}

void Mechanic::useAnalisysDevice() {
    printf("Analisys device has been used\n");
}

